# Generated by Django 4.1.6 on 2023-02-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_movimentorotativo_options_mensalista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalista',
            name='fim',
            field=models.DateField(blank=True, null=True),
        ),
    ]
