# Generated by Django 4.1.6 on 2023-02-11 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_movimentomensal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentomensal',
            options={'verbose_name_plural': 'movimentos mensais'},
        ),
    ]
