# Generated by Django 4.1.6 on 2023-02-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_movimentomensal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
