# Generated by Django 4.1.6 on 2023-02-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pessoa_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='documento',
        ),
    ]
